linters:
  enable:
    - bodyclose
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - misspell
    - nakedret
    - rowserrcheck
    - copyloopvar
    - stylecheck
    - unconvert
    - whitespace
    - wsl

run:
  deadline: 3m